spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:mydb;CASE_INSENSITIVE_IDENTIFIERS=TRUE
        username: sa
        password: ''
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                globally_quoted_identifiers: true
                validator:
                    apply_to_ddl: false
        show-sql: false
    sql:
        init:
            mode: always

logging:
    level:
        org.springframework.web: INFO
        org.hibernate: ERROR

log4j:
    debug: true